{
	"id": "CVE-2021-28677",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-28677",
				"description": "An issue was discovered in Pillow before 8.2.0. For EPS data, the readline implementation used in EPSImageFile has to deal with any combination of \\r and \\n as line endings. It used an accidentally quadratic method of accumulating lines while looking for a line ending. A malicious EPS file could use this to perform a DoS of Pillow in the open phase, before an image was accepted for opening.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
							"base_score": 5,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 5,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 5,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"NVD-CWE-noinfo"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/python-pillow/Pillow/pull/5377"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://security.gentoo.org/glsa/202107-33"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-28677"
					}
				],
				"published": "2021-06-02T16:15:08.827Z",
				"modified": "2023-11-07T03:32:18.45Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "8.2.0"
														}
													]
												}
											}
										]
									}
								]
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2021/CVE-2021-28677.json"
		]
	}
}
