{
	"id": "CVE-2021-41198",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-41198",
				"description": "TensorFlow is an open source platform for machine learning. In affected versions if `tf.tile` is called with a large input argument then the TensorFlow process will crash due to a `CHECK`-failure caused by an overflow. The number of elements in the output tensor is too much for the `int64_t` type and the overflow is detected via a `CHECK` statement. This aborts the process. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
							"base_score": 2.1,
							"nvd_base_severity": "LOW",
							"temporal_score": 2.1,
							"nvd_temporal_severity": "LOW",
							"environmental_score": 2.1,
							"nvd_environmental_severity": "LOW"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 5.5,
							"base_severity": "MEDIUM",
							"temporal_score": 5.5,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.5,
							"environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "security-advisories@github.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 5.5,
							"base_severity": "MEDIUM",
							"temporal_score": 5.5,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.5,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-190"
						]
					},
					{
						"source": "security-advisories@github.com",
						"cwe": [
							"CWE-190"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/tensorflow/tensorflow/commit/9294094df6fea79271778eb7e7ae1bad8b5ef98f"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/tensorflow/tensorflow/issues/46911"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2p25-55c9-h58q"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41198"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/commit/9294094df6fea79271778eb7e7ae1bad8b5ef98f"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/issues/46911"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2p25-55c9-h58q"
					}
				],
				"published": "2021-11-05T20:15:07.907Z",
				"modified": "2024-11-21T06:25:45.033Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"lt": "2.4.4"
																	}
																]
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"lt": "2.5.2",
																		"ge": "2.5.0"
																	}
																]
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"lt": "2.6.1",
																		"ge": "2.6.0"
																	}
																]
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2021/CVE-2021-41198.json"
		]
	}
}
