{
	"id": "CVE-2023-33976",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2023-33976",
				"description": "TensorFlow is an end-to-end open source platform for machine learning. `array_ops.upper_bound` causes a segfault when not given a rank 2 tensor. The fix will be included in TensorFlow 2.13 and will also cherrypick this commit on TensorFlow 2.12.",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "security-advisories@github.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "security-advisories@github.com",
						"cwe": [
							"CWE-190"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-33976"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/commit/6fa05df43b00038b048f4f0e51ef522da6532fec"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/commit/915884fdf5df34aaedd00fc6ace33a2cfdefa586"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gjh7-xx4r-x345"
					}
				],
				"published": "2024-07-30T20:15:03.023Z",
				"modified": "2024-07-31T12:57:02.3Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2023/CVE-2023-33976.json"
		]
	}
}
