{
	"id": "CVE-2020-25706",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-25706",
				"description": "A cross-site scripting (XSS) vulnerability exists in templates_import.php (Cacti 1.2.13) due to Improper escaping of error message during template import preview in the xml_path field",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
							"base_score": 4.3,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 4.3,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 4.3,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
							"base_score": 6.1,
							"base_severity": "MEDIUM",
							"temporal_score": 6.1,
							"temporal_severity": "MEDIUM",
							"environmental_score": 6.1,
							"environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "secalert@redhat.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
							"base_score": 5.4,
							"base_severity": "MEDIUM",
							"temporal_score": 5.4,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.4,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-79"
						]
					},
					{
						"source": "secalert@redhat.com",
						"cwe": [
							"CWE-79"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25706"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25706"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://github.com/Cacti/cacti/commit/39458efcd5286d50e6b7f905fedcdc1059354e6e"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://github.com/Cacti/cacti/issues/3723"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://lists.debian.org/debian-lts-announce/2022/12/msg00039.html"
					}
				],
				"published": "2020-11-12T14:15:22.97Z",
				"modified": "2023-11-07T03:20:23.327Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:cacti:cacti:1.2.13:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2020/CVE-2020-25706.json"
		]
	}
}
