{
	"id": "CVE-2020-1720",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-1720",
				"description": "A flaw was found in PostgreSQL's \"ALTER ... DEPENDS ON EXTENSION\", where sub-commands did not perform authorization checks. An authenticated attacker could use this flaw in certain configurations to perform drop objects such as function, triggers, et al., leading to database corruption. This issue affects PostgreSQL versions before 12.2, before 11.7, before 10.12 and before 9.6.17.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:S/C:N/I:P/A:N",
							"base_score": 3.5,
							"nvd_base_severity": "LOW",
							"temporal_score": 3.5,
							"nvd_temporal_severity": "LOW",
							"environmental_score": 3.5,
							"nvd_environmental_severity": "LOW"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
							"base_score": 6.5,
							"base_severity": "MEDIUM",
							"temporal_score": 6.5,
							"temporal_severity": "MEDIUM",
							"environmental_score": 6.5,
							"environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "secalert@redhat.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:L/A:N",
							"base_score": 3.1,
							"base_severity": "LOW",
							"temporal_score": 3.1,
							"temporal_severity": "LOW",
							"environmental_score": 3.1,
							"environmental_severity": "LOW"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-862"
						]
					},
					{
						"source": "secalert@redhat.com",
						"cwe": [
							"CWE-285"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-1720"
					},
					{
						"source": "secalert@redhat.com",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-08/msg00043.html"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1720"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://www.postgresql.org/about/news/2011/"
					}
				],
				"published": "2020-03-17T16:15:11.127Z",
				"modified": "2023-11-07T03:19:29.34Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:postgresql:postgresql:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "10.12",
															"ge": "10.0"
														}
													]
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:postgresql:postgresql:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "11.7",
															"ge": "11.0"
														}
													]
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:postgresql:postgresql:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "12.2",
															"ge": "12.0"
														}
													]
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:postgresql:postgresql:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"lt": "9.6.17",
															"ge": "9.6"
														}
													]
												}
											}
										]
									}
								]
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:redhat:decision_manager:7.0:*:*:*:*:*:*:*"
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:a:redhat:software_collections:-:*:*:*:*:*:*:*"
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"fix_status": {
													"class": "unknown"
												},
												"package": {
													"cpe": "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2020/CVE-2020-1720.json"
		]
	}
}
