{
	"id": "CVE-2020-15197",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-15197",
				"description": "In Tensorflow before version 2.3.1, the `SparseCountSparseOutput` implementation does not validate that the input arguments form a valid sparse tensor. In particular, there is no validation that the `indices` tensor has rank 2. This tensor must be a matrix because code assumes its elements are accessed as elements of a matrix. However, malicious users can pass in tensors of different rank, resulting in a `CHECK` assertion failure and a crash. This can be used to cause denial of service in serving installations, if users are allowed to control the components of the input sparse tensor. The issue is patched in commit 3cbb917b4714766030b28eba9fb41bb97ce9ee02 and is released in TensorFlow version 2.3.1.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:S/C:N/I:N/A:P",
							"base_score": 3.5,
							"nvd_base_severity": "LOW",
							"temporal_score": 3.5,
							"nvd_temporal_severity": "LOW",
							"environmental_score": 3.5,
							"nvd_environmental_severity": "LOW"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:N/I:N/A:H",
							"base_score": 6.3,
							"base_severity": "MEDIUM",
							"temporal_score": 6.3,
							"temporal_severity": "MEDIUM",
							"environmental_score": 6.3,
							"environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "security-advisories@github.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:N/I:N/A:H",
							"base_score": 6.3,
							"base_severity": "MEDIUM",
							"temporal_score": 6.3,
							"temporal_severity": "MEDIUM",
							"environmental_score": 6.3,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "security-advisories@github.com",
						"cwe": [
							"CWE-20",
							"CWE-617"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-15197"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/commit/3cbb917b4714766030b28eba9fb41bb97ce9ee02"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1"
					},
					{
						"source": "security-advisories@github.com",
						"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-qc53-44cj-vfvx"
					}
				],
				"published": "2020-09-25T19:15:14.963Z",
				"modified": "2021-08-17T13:21:51.16Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:google:tensorflow:2.3.0:*:*:*:-:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": "nvd-api-cve"
}
