{
	"id": "CVE-2020-7471",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-7471",
				"description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
							"base_score": 7.5,
							"nvd_base_severity": "HIGH",
							"temporal_score": 7.5,
							"nvd_temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"nvd_environmental_severity": "HIGH"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 9.8,
							"base_severity": "CRITICAL",
							"temporal_score": 9.8,
							"temporal_severity": "CRITICAL",
							"environmental_score": 9.8,
							"environmental_severity": "CRITICAL"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-89"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "http://www.openwall.com/lists/oss-security/2020/02/03/1"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://docs.djangoproject.com/en/3.0/releases/security/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://groups.google.com/forum/#%21topic/django-announce/X45S86X5bZI"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://seclists.org/bugtraq/2020/Feb/30"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://security.gentoo.org/glsa/202004-17"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://security.netapp.com/advisory/ntap-20200221-0006/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://usn.ubuntu.com/4264-1/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://www.debian.org/security/2020/dsa-4629"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://www.djangoproject.com/weblog/2020/feb/03/security-releases/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://www.openwall.com/lists/oss-security/2020/02/03/1"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-7471"
					}
				],
				"published": "2020-02-03T12:15:26.993Z",
				"modified": "2023-11-07T03:26:06.483Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
														},
														"affected": {
															"type": "semver",
															"range": [
																{
																	"lt": "1.11.28",
																	"ge": "1.11"
																}
															]
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
														},
														"affected": {
															"type": "semver",
															"range": [
																{
																	"lt": "2.2.10",
																	"ge": "2.2"
																}
															]
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
														},
														"affected": {
															"type": "semver",
															"range": [
																{
																	"lt": "3.0.3",
																	"ge": "3.0"
																}
															]
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2020/CVE-2020-7471.json"
		]
	}
}
