{
	"id": "CVE-2020-19500",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-19500",
				"description": "Rejected reason: DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-19500"
					}
				],
				"published": "2023-08-22T19:16:02.47Z",
				"modified": "2023-11-07T03:19:17.893Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2020/CVE-2020-19500.json"
		]
	}
}
