{
	"id": "CVE-2020-29243",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-29243",
				"description": "dhowden tag before 2020-11-19 allows \"panic: runtime error: index out of range\" via readAPICFrame.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
							"base_score": 4.3,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 4.3,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 4.3,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
							"base_score": 6.5,
							"base_severity": "MEDIUM",
							"temporal_score": 6.5,
							"temporal_severity": "MEDIUM",
							"environmental_score": 6.5,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-129"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/dhowden/tag/issues/80"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/dhowden/tag/issues/80"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-29243"
					}
				],
				"published": "2020-12-28T08:15:11.71Z",
				"modified": "2024-11-21T05:23:49.763Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:tag_project:tag:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"lt": "2020-11-19"
																	}
																]
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2020/CVE-2020-29243.json"
		]
	}
}
