{
	"id": "CVE-2019-4621",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-4621",
				"description": "IBM DataPower Gateway 7.6.0.0-7 throug 6.0.14 and 2018.4.1.0 through 2018.4.1.5 have a default administrator account that is enabled if the IPMI LAN channel is enabled. A remote attacker could use this account to gain unauthorised access to the BMC. IBM X-Force ID: 168883.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
							"base_score": 6.8,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 6.8,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 6.8,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 9.8,
							"base_severity": "CRITICAL",
							"temporal_score": 9.8,
							"temporal_severity": "CRITICAL",
							"environmental_score": 9.8,
							"environmental_severity": "CRITICAL"
						}
					},
					{
						"type": "cvss_v30",
						"source": "psirt@us.ibm.com",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 8.1,
							"base_severity": "HIGH",
							"temporal_score": 8.1,
							"temporal_severity": "HIGH",
							"environmental_score": 8.1,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-1188"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/168883"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://www.ibm.com/support/pages/node/1125615"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-4621"
					},
					{
						"source": "psirt@us.ibm.com",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/168883"
					},
					{
						"source": "psirt@us.ibm.com",
						"url": "https://www.ibm.com/support/pages/node/1125615"
					}
				],
				"published": "2019-12-09T23:15:11.577Z",
				"modified": "2024-11-21T04:43:53.167Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:ibm:datapower_gateway:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"le": "2018.4.1.5",
																		"ge": "2018.4.1.0"
																	}
																]
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:ibm:datapower_gateway:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"le": "7.6.0.14",
																		"ge": "7.6.0.0"
																	}
																]
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2019/CVE-2019-4621.json"
		]
	}
}
