{
	"id": "CVE-2019-6446",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-6446",
				"description": "An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
							"base_score": 7.5,
							"nvd_base_severity": "HIGH",
							"temporal_score": 7.5,
							"nvd_temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"nvd_environmental_severity": "HIGH"
						}
					},
					{
						"type": "cvss_v30",
						"source": "nvd@nist.gov",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 9.8,
							"base_severity": "CRITICAL",
							"temporal_score": 9.8,
							"temporal_severity": "CRITICAL",
							"environmental_score": 9.8,
							"environmental_severity": "CRITICAL"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-502"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.securityfocus.com/bid/106670"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://access.redhat.com/errata/RHSA-2019:3335"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://access.redhat.com/errata/RHSA-2019:3704"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/numpy/numpy/issues/12759"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.securityfocus.com/bid/106670"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://access.redhat.com/errata/RHSA-2019:3335"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://access.redhat.com/errata/RHSA-2019:3704"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/numpy/numpy/issues/12759"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
					}
				],
				"published": "2019-01-16T05:29:01.37Z",
				"modified": "2024-11-21T04:46:28.137Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"le": "1.16.0"
																	}
																]
															}
														}
													}
												]
											}
										]
									}
								]
							},
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:o:fedoraproject:fedora:30:*:*:*:*:*:*:*"
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2019/CVE-2019-6446.json"
		]
	}
}
