{
	"id": "CVE-2019-14858",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-14858",
				"description": "A vulnerability was found in Ansible engine 2.x up to 2.8 and Ansible tower 3.x up to 3.5. When a module has an argument_spec with sub parameters marked as no_log, passing an invalid parameter name to the module will cause the task to fail before the no_log options in the sub parameters are processed. As a result, data in the sub parameter fields will not be masked and will be displayed if Ansible is run with increased verbosity and present in the module invocation arguments for the task.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:L/AC:L/Au:N/C:P/I:N/A:N",
							"base_score": 2.1,
							"nvd_base_severity": "LOW",
							"temporal_score": 2.1,
							"nvd_temporal_severity": "LOW",
							"environmental_score": 2.1,
							"nvd_environmental_severity": "LOW"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
							"base_score": 5.5,
							"base_severity": "MEDIUM",
							"temporal_score": 5.5,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.5,
							"environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v30",
						"source": "secalert@redhat.com",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H",
							"base_score": 7.3,
							"base_severity": "HIGH",
							"temporal_score": 7.3,
							"temporal_severity": "HIGH",
							"environmental_score": 7.3,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-532"
						]
					},
					{
						"source": "secalert@redhat.com",
						"cwe": [
							"CWE-117",
							"CWE-532"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14858"
					},
					{
						"source": "secalert@redhat.com",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html"
					},
					{
						"source": "secalert@redhat.com",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2019:3201"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2019:3202"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2019:3203"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2019:3207"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2020:0756"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14858"
					}
				],
				"published": "2019-10-14T15:15:09.927Z",
				"modified": "2019-10-24T23:15:12.727Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:redhat:ansible_engine:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"le": "2.8.0",
															"ge": "2.0"
														}
													]
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:redhat:ansible_tower:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"le": "3.5.0",
															"ge": "3.0"
														}
													]
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2019/CVE-2019-14858.json"
		]
	}
}
