{
	"id": "CVE-2019-10051",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-10051",
				"description": "An issue was discovered in Suricata 4.1.3. If the function filetracker_newchunk encounters an unsafe \"Some(sfcm) => { ft.new_chunk }\" item, then the program enters an smb/files.rs error condition and crashes.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
							"base_score": 5,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 5,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 5,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v30",
						"source": "nvd@nist.gov",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-754"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/OISF/suricata/pull/3734"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://redmine.openinfosecfoundation.org/issues/2896"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://suricata-ids.org/2019/04/30/suricata-4-1-4-released/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/OISF/suricata/pull/3734"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://redmine.openinfosecfoundation.org/issues/2896"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://suricata-ids.org/2019/04/30/suricata-4-1-4-released/"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-10051"
					}
				],
				"published": "2019-08-28T20:15:10.327Z",
				"modified": "2024-11-21T04:18:17.197Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"type": "cpe",
																"cpe": "cpe:2.3:a:suricata-ids:suricata:4.1.3:*:*:*:*:*:*:*"
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"type": "cpe",
																"cpe": "cpe:2.3:a:suricata-ids:suricata:4.1.4:*:*:*:*:*:*:*"
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2019/CVE-2019-10051.json"
		]
	}
}
