{
	"id": "CVE-2019-19998",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-19998",
				"description": "Xiuno BBS 4.0 allows XXE via plugin/xn_wechat_public/route/token.php.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
							"base_score": 5,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 5,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 5,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-611"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "https://gitee.com/xiuno/xiunobbs/issues/I177MY"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-19998"
					}
				],
				"published": "2019-12-26T04:15:10.86Z",
				"modified": "2020-01-07T15:20:04.817Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:xiuno:xiunobbs:4.0:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": "nvd-api-cve"
}
