{
	"id": "CVE-2016-2512",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2016-2512",
				"description": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
							"base_score": 4.3,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 4.3,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 4.3,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v30",
						"source": "nvd@nist.gov",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:H/A:N",
							"base_score": 7.4,
							"base_severity": "HIGH",
							"temporal_score": 7.4,
							"temporal_severity": "HIGH",
							"environmental_score": 7.4,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-79"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0502.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0504.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0505.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0506.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.debian.org/security/2016/dsa-3544"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.securityfocus.com/bid/83879"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.securitytracker.com/id/1035152"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.ubuntu.com/usn/USN-2915-1"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.ubuntu.com/usn/USN-2915-2"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "http://www.ubuntu.com/usn/USN-2915-3"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://www.djangoproject.com/weblog/2016/mar/01/security-releases/"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0502.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0504.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0505.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0506.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.debian.org/security/2016/dsa-3544"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.securityfocus.com/bid/83879"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.securitytracker.com/id/1035152"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.ubuntu.com/usn/USN-2915-1"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.ubuntu.com/usn/USN-2915-2"
					},
					{
						"source": "cve@mitre.org",
						"url": "http://www.ubuntu.com/usn/USN-2915-3"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://www.djangoproject.com/weblog/2016/mar/01/security-releases/"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2016-2512"
					}
				],
				"published": "2016-04-08T15:59:06.183Z",
				"modified": "2024-11-21T02:48:35.683Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:djangoproject:django:1.8.9:*:*:*:*:*:*:*"
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:djangoproject:django:1.9.1:*:*:*:*:*:*:*"
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:djangoproject:django:1.9.2:*:*:*:*:*:*:*"
															}
														}
													}
												]
											},
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:djangoproject:django:1.9:*:*:*:*:*:*:*"
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2016/CVE-2016-2512.json"
		]
	}
}
