{
	"id": "CVE-2016-4899",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2016-4899",
				"description": "The datamover module in the Linux version of NovaBACKUP DataCenter before 09.06.03.0353 is vulnerable to remote command execution via unspecified attack vectors.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
							"base_score": 10,
							"nvd_base_severity": "HIGH",
							"temporal_score": 10,
							"nvd_temporal_severity": "HIGH",
							"environmental_score": 10,
							"nvd_environmental_severity": "HIGH"
						}
					},
					{
						"type": "cvss_v30",
						"source": "nvd@nist.gov",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 9.8,
							"base_severity": "CRITICAL",
							"temporal_score": 9.8,
							"temporal_severity": "CRITICAL",
							"environmental_score": 9.8,
							"environmental_severity": "CRITICAL"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-20"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://www.viestintavirasto.fi/en/cybersecurity/vulnerabilities/2016/haavoittuvuus-2016-134.html"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2016-4899"
					},
					{
						"source": "vultures@jpcert.or.jp",
						"url": "https://www.viestintavirasto.fi/en/cybersecurity/vulnerabilities/2016/haavoittuvuus-2016-134.html"
					}
				],
				"published": "2017-04-13T17:59:00.623Z",
				"modified": "2024-11-21T02:53:12.3Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"cpe": "cpe:2.3:a:novastor:novabackup_datacenter:-:*:*:*:*:*:*:*"
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2016/CVE-2016-4899.json"
		]
	}
}
