{
	"id": "CVE-2022-42964",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-42964",
				"description": "An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the pymatgen PyPI package, when an attacker is able to supply arbitrary input to the GaussianInput.from_string method",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					},
					{
						"type": "cvss_v31",
						"source": "reefs@jfrog.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 5.9,
							"base_severity": "MEDIUM",
							"temporal_score": 5.9,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.9,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-1333"
						]
					},
					{
						"source": "reefs@jfrog.com",
						"cwe": [
							"CWE-1333"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42964"
					},
					{
						"source": "reefs@jfrog.com",
						"url": "https://research.jfrog.com/vulnerabilities/pymatgen-redos-xray-257184/"
					}
				],
				"published": "2022-11-09T20:15:09.793Z",
				"modified": "2023-07-06T13:52:56.227Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:pymatgen:pymatgen:-:*:*:*:*:*:*:*"
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2022/CVE-2022-42964.json"
		]
	}
}
